In [1]:
from sympy import *
init_session()
from IPython.display import display_latex

IPython console for SymPy 1.10.1 (Python 3.9.13-64-bit) (ground types: gmpy)

These commands were executed:
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)
>>> init_printing()

Documentation can be found at https://docs.sympy.org/1.10.1/



In [2]:
# p78e1

u, v, w = [Point3D(2,0,-1),Point3D(-3,1,2), Point3D(4,-2,7)]
5*u+6*v, u+v-w, 2*u-v+1/3*w

In [5]:
# p78e2

u, v, w, s = [Point3D(1,2,3),Point3D(-4,1,7), Point3D(0,-2,-5), Point3D(-2,-1,-3)]

Matrix([s,v,w]).T.det(), Matrix([u,s,w]).T.det() , Matrix([u,v,s]).T.det(), solve(list((Matrix([u,v,w]).T*Matrix(3,1,[x,y,z])-Matrix(3,1,list(s))).T))


In [33]:
# p78e4

u, v, w = [Point(0,1,1),Point(1,2,3), Point(5,7,12)]

A=Matrix([u,v,w]).T
A.det()


b=Matrix(3,1,[0,0,0])
AA=A.row_join(b)
AA, AA.LUdecomposition()[1]


⎛⎡0  1  5   0⎤  ⎡1  2  7  0⎤⎞
⎜⎢           ⎥  ⎢          ⎥⎟
⎜⎢1  2  7   0⎥, ⎢0  1  5  0⎥⎟
⎜⎢           ⎥  ⎢          ⎥⎟
⎝⎣1  3  12  0⎦  ⎣0  0  0  0⎦⎠

In [55]:
# p78e5

datos=[
    [[4,1,-5], [2,3,-8],[1,6,2]],
    [[4,1,-5], [2,3,-8],[10,0,-7]],
    [[2,0,9], [3,-1,2],[5,-1,4]],
    [[3,-2,5], [-3,5,2],[1,1,6]],
    [[1,-2,-3], [-2,4,4],[-6,3,0]],
    
]
for d in datos:   
    u, v, w = [Point(i) for i  in d]
    ld = True if Matrix([u,v,w]).det()==0 else False
    sol_latex=r"${} \to  {}={} \to {} $".format(latex(Matrix([u,v,w])),
                                         latex(Matrix([u,v,w])).replace(r"[",r"|").replace(r"]",r"|"),
                                         latex(Matrix([u,v,w]).det()),
                                         R"Linealmente \ Dependientes" if ld == True else "Linealmente \ Independientes"
                                              )
    display_latex(sol_latex,raw=True)


In [3]:
# p78e5

datos=[
    [[4,1,-5], [2,3,-8],[10,0,-7],[1,6,2]],
    [[1,4,7], [2,5,8],[3,6,9],[1,3,5]],
    
]
for d in datos:   
    
    A = Matrix([Point(i) for i  in d])
    ld = True if Matrix([u,v,w]).det()==0 else False
    sol_latex=r"$A={} \to  ran(A)={}$".format(latex(A),
                                         latex(A.rank()),
                                              )
    display_latex(sol_latex,raw=True)


In [18]:
# p79e7

u, v, w , a= [Point(0,1,1),Point(1,0,1), Point(1,1,0), Point(1,2,3)]


sol_latex=r"${} \to  {}={} $".format(latex(Matrix([u,v,w])),
                                     latex(Matrix([u,v,w])).replace(r"[",r"|").replace(r"]",r"|"),
                                     latex(Matrix([u,v,w]).det()),
                                    )                                          
display_latex(sol_latex,raw=True)


sol_latex=r"${}\cdot{}={} \to {}={} $".format(latex(Matrix([u,v,w]).T),
                                     latex(Matrix(3,1,['a','b','c'])),
                                    latex(Matrix(3,1,a)),
                                              latex(Matrix(3,1,['a','b','c'])),
                                              latex(Matrix([u,v,w]).T.inv()*Matrix(3,1,a))
                                    )                                          
display_latex(sol_latex,raw=True)
 


In [19]:
# p79e8

u, v, w , a= [Point(-1,1,1),Point(1,-1,1), Point(1,1,-1), Point(2,4,2)]


sol_latex=r"${} \to  {}={} $".format(latex(Matrix([u,v,w])),
                                     latex(Matrix([u,v,w])).replace(r"[",r"|").replace(r"]",r"|"),
                                     latex(Matrix([u,v,w]).det()),
                                    )                                          
display_latex(sol_latex,raw=True)


sol_latex=r"${}\cdot{}={} \to {}={} $".format(latex(Matrix([u,v,w]).T),
                                     latex(Matrix(3,1,['a','b','c'])),
                                    latex(Matrix(3,1,a)),
                                              latex(Matrix(3,1,['a','b','c'])),
                                              latex(Matrix([u,v,w]).T.inv()*Matrix(3,1,a))
                                    )                                          
display_latex(sol_latex,raw=True)
 

In [58]:
# p79e9

a = symbols('a')

u, v, w= [Point(-2,a,a),Point(a,-2,a), Point(a,1,-2)]


sol_latex=r"${} \to  {}={} $".format(latex(Matrix([u,v,w])),
                                     latex(Matrix([u,v,w])).replace(r"[",r"|").replace(r"]",r"|"),
                                     latex(factor(Matrix([u,v,w]).det())),
                                    )                                          
display_latex(sol_latex,raw=True)

# for v in solve(factor(Matrix([u,v,w]).det()),a):
#     display(v)
#     display_latex(latex(Matrix([u,v,w])).subs(a,v),raw=True)
    
for i in solve(factor(Matrix([u,v,w]).det()),a) :
        display(i)
        display_latex("$"+latex(Matrix([u,v,w]).subs(a,i))+
                      r"\to"+latex("ran(A)=")+
                      latex(Matrix([u,v,w]).subs(a,i).rank())+
                      "$",raw=True)

In [59]:
# p79e10

A, B, C=[Point(7,2,-1),Point(1,6,-3),Point(3,4,5)]

B-A, C+B-A

In [60]:
# p79e11

a = symbols('a')

u, v, w= [Point(a,3,1),Point(1,1,a), Point(1,1,1)]


sol_latex=r"${} \to  {}={} $".format(latex(Matrix([u,v,w])),
                                     latex(Matrix([u,v,w])).replace(r"[",r"|").replace(r"]",r"|"),
                                     latex(factor(Matrix([u,v,w]).det())),
                                    )                                          
display_latex(sol_latex,raw=True)


    


In [4]:
# p79e12

u, v, w , a= [Point(1,2,1),Point(2,1,0), Point(0,1,3), Point(-3,3,10)]


sol_latex=r"${} \to  {}={} $".format(latex(Matrix([u,v,w])),
                                     latex(Matrix([u,v,w])).replace(r"[",r"|").replace(r"]",r"|"),
                                     latex(Matrix([u,v,w]).det()),
                                    )                                          
display_latex(sol_latex,raw=True)


sol_latex=r"${}\cdot{}={} \to {}={} $".format(latex(Matrix([u,v,w]).T),
                                     latex(Matrix(3,1,['a','b','c'])),
                                    latex(Matrix(3,1,a)),
                                              latex(Matrix(3,1,['a','b','c'])),
                                              latex(Matrix([u,v,w]).T.inv()*Matrix(3,1,a))
                                    )                                          
display_latex(sol_latex,raw=True)

In [9]:
# p79e13
A, B =[[-3,6,10],[6,0,-2]]
AB=Point(B)-Point(A)
AB, Point(A)+AB/3, Point(A)+2*AB/3

In [11]:
# p79e14

a = symbols('a')

u, v, w= [Point(a,a,1),Point(2,a,2), Point(0,0,a)]


sol_latex=r"${} \to  {}={} $".format(latex(Matrix([u,v,w])),
                                     latex(Matrix([u,v,w])).replace(r"[",r"|").replace(r"]",r"|"),
                                     latex(factor(Matrix([u,v,w]).det())),
                                    )                                          
display_latex(sol_latex,raw=True)

In [21]:
# p79e15
A, B, C =[[1,3,5],[2,1,4],[-3,0,1]]
BC=Point(C)-Point(B)
D=Point(A)+BC
AC=Point(C)-Point(A)

BC, D ,AC, Point(A)+AC/2

# Ejercicios de EVAU


In [43]:
# Julio 22

A,B,C, D =[[1,1,1],[-2,1,0],[0,1,3],[0,y,0]]

A=Matrix([Point(B)-Point(A),Point(C)-Point(A),Point(D)-Point(A)])

sol_latex=r"${} \to  {}={} $".format(latex(A),
                                     latex(A).replace(r"[",r"|").replace(r"]",r"|"),
                                     latex(A.det()))

display_latex(sol_latex,raw=True)

In [6]:
# Junio 22

u,v,P,Q =[Point([3,1,1]),Point([6,-2,1]),Point([0,-2,0]),Point([-1,0,0])]

A=Matrix([u,v,Q-P])

sol_latex=r"${} \to  {}={} $".format(latex(A),
                                     latex(A).replace(r"[",r"|").replace(r"]",r"|"),
                                     latex(A.det()))

display_latex(sol_latex,raw=True)

A=Matrix([u,v,Point(2,k,2*k)])

sol_latex=r"${} \to  {}={} $".format(latex(A),
                                     latex(A).replace(r"[",r"|").replace(r"]",r"|"),
                                     latex(A.det()))

display_latex(sol_latex,raw=True)

In [9]:
# Junio 22.2a

a = symbols('a')

u,v = [Point([a,-2,3]),Point([-1,a,1])]
u.dot(v)

In [10]:
# Junio 22.2b

u,v = [Point([1,0,-2]),Point([3,1,0])]

A=Matrix([u,v,u+v])

sol_latex=r"${} \to  {}={} $".format(latex(A),
                                     latex(A).replace(r"[",r"|").replace(r"]",r"|"),
                                     latex(A.det()))

display_latex(sol_latex,raw=True)



In [18]:
# Julio 21
import numpy as np

A, B, C, D =[Point([1,0,1]),Point([3,1,0]),Point(2,-1,1), Point([1,-2,0])]
B-A, C-A,np.cross(B-A, C-A), Line3D(D,direction_ratio=np.cross(B-A, C-A)).equation()

(Point3D(2, 1, -1),
 Point3D(1, -1, 0),
 array([-1, -1, -3], dtype=object),
 (-x + y + 3, -3*x + z + 3))

In [2]:
# Junio 21

from sympy import Plane
import numpy as np

A, B, C, D = [Point([0,1,1]),Point([-1,0,2]),Point([1,3,1]),Point([2,-1,0])]
p2=Plane(Point(1,0,0),normal_vector=(1,0,2))

Plane(B,C,D).equation(), Plane(B,C,D).normal_vector, C-B, D-B, np.cross(C-B, D-B),np.cross((1,0,2),np.cross(C-B, D-B))
Line(A, direction_ratio=np.cross(p2.normal_vector,np.cross(C-B, D-B))).equation(), Line(A, direction_ratio=p2.intersection(Plane(B,C,D))[0].direction).equation()


In [13]:
# Junio 21.2


u1, u2, u3, u4 = Point(-1,1,1), Point(0,3,1), Point(1, -2, 0), Point(-2,0,1)

v1, v2, v3 = 2*u1-u2, u1+u3, u4

Matrix([v1,v2,v3]), Matrix([v1,v2,v3]).det(), np.dot(2*u1-u2,2*u1-u2), u4-u1, np.cross(u4-u1,u4-u1)

(Matrix([
 [-2, -1, 1],
 [ 0, -1, 1],
 [-2,  0, 1]]),
 2,
 6,
 Point3D(-1, -1, 0),
 array([0, 0, 0], dtype=object))

In [26]:
# Septiembre 20

Line(Point(0,-1/3,7/3), direction_ratio=(np.cross(Point(3,1,-4),Point(2,1,-1)))).equation()

np.cross(Point(3,1,-4),Point(2,1,-1))


M=Matrix([Point(x,y,z)-Point(0,-7/3,-1/3),np.cross(Point(3,1,-4),Point(2,1,-1)),Point(2,-1,3)])
M, M.det()

⎛⎡x  y + 7/3  z + 1/3⎤                        ⎞
⎜⎢                   ⎥                        ⎟
⎜⎢3    -5        1   ⎥, -14⋅x - 7⋅y + 7⋅z - 14⎟
⎜⎢                   ⎥                        ⎟
⎝⎣2    -1        3   ⎦                        ⎠

In [28]:
# Junio 20

P, A, B = Point(0,0,1), Point(1,1,0), Point(0,3,1)

M=Matrix([Point(x,y,z)-P,B-A,P-A])
M, M.det()

⎛⎡x   y   z - 1⎤               ⎞
⎜⎢             ⎥               ⎟
⎜⎢-1  2     1  ⎥, 3⋅x + 3⋅z - 3⎟
⎜⎢             ⎥               ⎟
⎝⎣-1  -1    1  ⎦               ⎠

In [58]:
# Septiembre 19

A, p1, p2=Point(1,3,-1),Plane(Point(0,-1,0),normal_vector=(3,1,0)),Plane(Point(0,2,-1),normal_vector=(0,4,3))
r= p1.intersection(p2)[0]
P=r.points[0]
p1.equation(), p2.equation(),r,P 
Plane(A,normal_vector=np.cross(r.direction, A-P)).equation()

In [65]:
# Septiembre 19

A, p1, p2=Point(1,3,2),Plane(Point(0,1/2,0),normal_vector=(3,-2,0)),Plane(Point(0,0,1),normal_vector=(0,2,3))
r= p1.intersection(p2)[0]
P=r.points[0]
p1.equation(), p2.equation()
r,P,np.cross(p1.normal_vector, p2.normal_vector),Plane(A,normal_vector=np.cross(p1.normal_vector, p2.normal_vector)).equation()

(Line3D(Point3D(2/3, 3/2, 0), Point3D(-16/3, -15/2, 6)),
 Point3D(2/3, 3/2, 0),
 array([-6, -9, 6], dtype=object),
 -6*x - 9*y + 6*z + 21)

In [77]:
# Septiembre 19

u, v = Point(1,1,1), Point(2,1,0)

list(np.cross(u,v)), Matrix([u,v,np.cross(u,v)]), Matrix([u,v,np.cross(u,v)]).det()

⎛             ⎡1   1  1 ⎤   ⎞
⎜             ⎢         ⎥   ⎟
⎜[-1, 2, -1], ⎢2   1  0 ⎥, 6⎟
⎜             ⎢         ⎥   ⎟
⎝             ⎣-1  2  -1⎦   ⎠

In [3]:
# Septiembre 19

A, p1, p2=Point(1,3,-1),Plane(Point(0,-1,0),normal_vector=(3,1,0)),Plane(Point(0,2,-1),normal_vector=(0,4,3))
r= p1.intersection(p2)[0]
P=r.points[0]
p1.equation(), p2.equation(),r,P 
Plane(Point(x,y,z)-P,normal_vector=np.cross(r.direction, A-P)).equation()

NameError: name 'u' is not defined

In [8]:
# Junio 19

P,A, u = Point(2,1,2),Point(1,0,0), Point(-1,1,1)

Matrix([Point(x,y,z)-P,u,P-A]).det()

In [11]:
# Junio 19.b

u, v = Point(1,2,0),Point(2,1,-3)

Matrix([Point(x,y,z),u,v]).det()

Problema 19.1.3 (2,5 puntos) Dados los puntos $A(1, 2, −3)$; $B(1, 5, 0)$; $C(5, 6, −1)$ y $D(4, −1, 3)$,
se pide:

    * Calcular el plano $\pi$ que contiene a los puntos $A$,$B$ y $C$
    * Calcular el volumen del tetraedro determinado por los cuatro puntos
    * Calcular el área del triángulo determinado por $A$,$B$ y $C$ 

In [23]:
# Madrid 19.1.3

A, B, C, D = Point(1, 2, -3), Point(1, 5, 0), Point(5, 6, -1), Point(4, -1, 3) 

simplify(Eq(Plane(A,B,C).equation(),0)), abs(Matrix([B-A,C-A,D-A]).det()/6), Point(np.cross(B-A, C-A)).distance((0,0,0))/

In [2]:

u, v, w = [Point(i) for i  in [[4,1,-5], [2,3,-8],[10,0,-7]]]

latex(Matrix([u,v,w]))
display_latex(latex(Matrix([u,v,w])), raw=True)

In [52]:
display_latex?
